config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :stories, only: [:create, :destroy]
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to:  "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]
  resources :users, only: [:show, :index]

  resources :chats, only: [:show] do
    resources :messages, only: [:create], param: :chat_id
  end

  post "follow", to: 'follows#follow', as: :follow
  delete 'unfollow', to: 'follows#unfollow', as: :unfollow
  delete 'cancel_request', to: 'follows#cancel_request', as: :cancel_request

  post 'accept_follow', to: 'follows#accept_follow', as: :accept_follow
  delete 'decline_follow', to: 'follows#decline_follow', as: :decline_follow
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :chat_users
  has_many :users, through: :chat_users
  has_many :messages, dependent: :destroy

  def other_user_username(current_user)
    other_user = users.joins(:chat_users).where.not(id: current_user.id).first
    other_user.username
  end
end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  before_create :check_privacy
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"

  def accept
    self.update(accepted: true)
  end

  private
  
  def check_privacy
    self.accepted = true unless self.followed.private
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :images, presence: true, blob: { content_type: :image }

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :image, presence: true, blob: { content_type: :image }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_pic

  has_many :chat_users
  has_many :chats, through: :chat_users
  has_many :messages, dependent: :destroy

  has_many :posts
  has_many :stories
  has_many :likes
  has_many :comments
  has_many :follow_requests, -> { where(accepted: false) }, class_name: "Follow", foreign_key: "followed_id"
  has_many :accepted_recieved_requests, -> { where(accepted: true) }, class_name: "Follow", foreign_key: "followed_id"
  has_many :waiting_sent_requests, -> {where(accepted: false) }, class_name: "Follow", foreign_key: "follower_id"
  has_many :accepted_sent_requests, -> { where(accepted: true) }, class_name: "Follow", foreign_key: "follower_id"
  has_many :waiting_followings, through: :waiting_sent_requests, source: :followed
  has_many :followers, through: :accepted_recieved_requests, source: :follower
  has_many :followings, through: :accepted_sent_requests, source: :followed

  def follow(user)
    Follow.create(follower: self, followed: user)
  end

  def unfollow(user)
    self.accepted_sent_requests.find_by(followed: user)&.destroy
  end

  def cancel_request(user)
    self.waiting_sent_requests.find_by(followed: user)&.destroy
  end


end

app/helpers/chat_users_helper.rb
module ChatUsersHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% if notice && notice.is_a?(Array)%>
  <% notice.each do |n| %>
  <p class="alert alert-success"> <%= n %> </p>
  <% end %>
<% elsif notice && notice.is_a?(String) %>
  <p class="alert alert-success"> <%= notice %> </p>
<% end %>
<% if alert && alert.is_a?(Array)%>
  <% alert.each do |a| %>
    <p class="alert alert-danger"> <%= a %> </p>
  <% end %>
<% elsif alert && alert.is_a?(String)%>
  <p class="alert alert-danger"> <%= alert %> </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light sticky-top bg-white border-bottom" style="border-color: #afafaf">
  <div class="container-fluid w-75 " >
    <%= link_to root_path, class:"navbar-brand" do %>
      <%= image_tag 'logo.png', width: "100rem" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
         <%= form_with(url: users_path, method: :get, data: {turbo_frame: "search_results", controller: "search-results"}, class:"d-flex") do |f| %>

          <div class="dropdown">
            <%= f.text_field :search_query, class: "form-control me-2 border-0 ", type:"search", placeholder:"🔍 Search",
                "aria-label"=>"Search", style: "background: #efefef;  width: 20rem;", "data-bs-toggle"=>"dropdown", "aria-expanded"=>"false",
                data: {action: "input->search-results#search"} %>

            <ul class="dropdown-menu p-4 mt-2" style="width:25rem">
              <%= render 'layouts/search_results', users: [] %>
            </ul>
          </div>

        <% end %>
      </div>
      <div class="navbar-collapse gap-4">
        <%=  link_to root_path, class: "text-dark" do %> <i class="fa-solid fa-house fa-xl"></i> <% end %>
        <% if current_user.chats.any? %>
          <%= link_to chat_path(current_user.chats.first.id), class: "text-dark" do %>
            <i class="fa-brands fa-facebook-messenger fa-xl"></i>
          <% end %>
        <% end %>
         <a type="button" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          <i class="fa-regular fa-square-plus fa-xl"></i>
        </a>

        <div class="dropstart">
          <i class="fa-solid fa-user-plus fa-xl" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <ul class="dropdown-menu p-4">
            <% current_user.follow_requests.each do |fr| %>
              <li>
                <div class="d-flex justify-content-between">
                  <div class="d-flex">
                     <%= cl_image_tag fr.follower.profile_pic.attached? ? fr.follower.profile_pic.key : 'user-pp_xuzmvv', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
                    <div class="d-flex flex-column mx-3 justify-content-center">
                      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:5rem"><%= link_to fr.follower, class:  "a-decoration-none" do %><%= fr.follower.username %><% end %></small>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center justify-content-between", style="width: 10.5rem">
                    <%= button_to accept_follow_path(follow_id: fr.id), method: :post, class:"btn btn-primary", style: "text-decoration:none" do %>
                      <small class="fw-bold text-white">Accept</small>
                    <% end %>
                    <%= button_to decline_follow_path(follow_id: fr.id), method: :delete, class:"btn btn-danger", style: "text-decoration:none" do %>
                      <small class="fw-bold text-white">Decline</small>
                    <% end %>
                  </div>

                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="dropdown">
          <a class="" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user && current_user.profile_pic.attached? %>
              <%= cl_image_tag current_user.profile_pic.key, class: "rounded-circle", style: "width: 2.5rem; height:2.5rem;  border: 2px solid #ccc" %>
            <% else %>
              <%= cl_image_tag 'user-pp_xuzmvv', class: "rounded-circle", style: "width: 2.5rem; height:2.5rem;  border: 2px solid #ccc" %>
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= button_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete%>
            </li>
          </ul>
        </div>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= button_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete%>
            </li>
          </ul>
        </div>


      </div>
    </div>
  </div>
</nav>

<%= render 'posts/form', post: Post.new %>

app/views/layouts/_search_results.html.erb
<%= turbo_frame_tag "search_results" do %>
  <% users.each do |u| %>
    <li class="mt-3">
      <div class="d-flex justify-content-between">
        <div class="d-flex">
          <%= cl_image_tag u.profile_pic.attached? ? u.profile_pic.key : 'user-pp_xuzmvv', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
          <div class="d-flex flex-column mx-3 justify-content-center">
            <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to u, class:  "a-decoration-none", data: {turbo: false} do %><%= u.username %><% end %></small>
          </div>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('petstagram.png') %>
  </head>

  <body>
  <% if current_user %>
      <%= render 'layouts/navbar' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_follow_state.html.erb
<% if current_user.followings.include?(user) %>
    <%= button_to "Unfollow", unfollow_path(user_id: user.id), method: :delete, class:"btn btn-danger", data: {turbo: 'false'}%>
<% elsif current_user.waiting_followings.include?(user) %>
  <%= button_to "Cancel", cancel_request_path(user_id: user.id), method: :delete, class:"btn btn-secondary", data: {turbo: 'false'}%>
<% elsif current_user == user %>
<% else %>
  <%= button_to "Follow", follow_path(user_id: user.id), method: :post, class:"btn btn-primary", data: {turbo: 'false'}%>
<% end%>

app/views/suggestions/_suggestion.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
      <%= cl_image_tag suggestion.profile_pic.attached? ? suggestion.profile_pic.key : 'user-pp_xuzmvv', class: "rounded-circle", style: "width: 2.5rem; height:2.5rem; object-fit:cover; border: 2px solid #ccc" %>
    <div class="d-flex flex-column mx-3">
       <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to suggestion, class:  "a-decoration-none", data: {turbo: 'false'} do %><%= suggestion.username %><% end %></small>
      <small class="text-muted" style="font-size:.7rem;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem">Suggested for you by Petstagram</small>
    </div>
  </div>

  <% if current_user.waiting_followings.include?(suggestion) %>
    <%= button_to cancel_request_path(user_id: suggestion.id), method: :delete, class:"btn bg-transparent border-0", data: {turbo: 'false'} do %>
      <small class="fw-bold text-secondary">Cancel</small>
    <% end %>
  <% else %>
    <%= button_to follow_path(user_id: suggestion.id), method: :post, class:"btn bg-transparent border-0", data: {turbo: 'false'} do %>
      <small class="fw-bold text-primary">Follow</small>
    <% end %>
  <% end %>
</div>

app/views/suggestions/_suggestions_list.html.erb
<div class="" style="width: 20rem">
  <div class="d-flex flex-row justify-content-between">
    <p class="text-muted fw-bold">Suggestions For You</p>
    <%= link_to root_path, style:"text-decoration:none" do%>
      <small class="fw-bold text-dark">See All</small>
    <% end %>
  </div>

  <div class="d-flex flex-column gap-3 px-2">
     <% suggestions.each do |suggestion| %>
      <%= render 'suggestions/suggestion', suggestion: suggestion %>
    <% end %>
  </div>
</div>